sonar.projectKey=k8s-no-eureka-template
sonar.projectName=k8s-no-eureka-template
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.sources=api-gateway/src/main/java,service-a/src/main/java,service-b/src/main/java
sonar.tests=api-gateway/src/test/java,service-a/src/test/java,service-b/src/test/java
sonar.java.binaries=api-gateway/target/classes,service-a/target/classes,service-b/target/classes
